<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::create(['code'=>'ACI00001','name'=>'ACIDO MURIATICO KAZVEL X GALON','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'ALC00002','name'=>'ALCOHOL ALKOFARMA 70 X 1 LT','category_id'=>'1','unit_id'=>'1']);
        Product::create(['code'=>'ALC00003','name'=>'ALCOHOL ALKOFARMA GEL X 1 LT','category_id'=>'1','unit_id'=>'1']);
        Product::create(['code'=>'ALC00004','name'=>'ALCOHOL EBRIEL EN GEL SACHET X 800 ML CAJ X 12 UND','category_id'=>'1','unit_id'=>'1']);
        Product::create(['code'=>'ALC00005','name'=>'ALCOHOL ISOPROPILICO X 1 LT','category_id'=>'1','unit_id'=>'1']);
        Product::create(['code'=>'AMB00006','name'=>'AMBIENTADOR GLADE AUTOMATICO CON DISPENSADOR 270 ML','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'AMB00007','name'=>'AMBIENTADOR GLADE REPUESTO AUTOMATICO 270 ML','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'AMB00008','name'=>'AMBIENTADOR GLADE  SPRAY 400 ML','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'AMB00009','name'=>'AMBIENTADOR SAPOLIO REPUESTO AUTOMATICO 240 ML FLORES','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'BAL00010','name'=>'BALDE 17 LT','category_id'=>'16','unit_id'=>'1']);
        Product::create(['code'=>'BOL00011','name'=>'BOLSA BLANCA 35 LT PAQ X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00012','name'=>'BOLSA NEGRA 240 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00013','name'=>'BOLSA NEGRA 220 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00014','name'=>'BOLSA NEGRA 180 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00015','name'=>'BOLSA NEGRA 140 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00016','name'=>'BOLSA NEGRA 75 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00017','name'=>'BOLSA NEGRA 50 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00018','name'=>'BOLSA NEGRA 35 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00019','name'=>'BOLSA NEGRA 26X40 X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00020','name'=>'BOLSA NEGRA 20*30 X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00021','name'=>'BOLSA NEGRA 18*26* X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00022','name'=>'BOLSA ROJA 180 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00023','name'=>'BOLSA ROJA 140 LT X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00024','name'=>'BOLSA ROJA 20X30 X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'BOL00025','name'=>'BOLSA ROJA 26X40 X 100 UND','category_id'=>'12','unit_id'=>'1']);
        Product::create(['code'=>'CER00026','name'=>'CERA LIQUIDA X GALON GOLDEN','category_id'=>'4','unit_id'=>'1']);
        Product::create(['code'=>'CER00027','name'=>'CERA LIQUIDA X GALON KAZVEL','category_id'=>'4','unit_id'=>'1']);
        Product::create(['code'=>'CER00028','name'=>'CERA TEKNO PASTA ROJA BALDE','category_id'=>'4','unit_id'=>'1']);
        Product::create(['code'=>'CHA00029','name'=>'CHAMPU ALFOMBRA KAZVEL X GALON','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'CRE00030','name'=>'CREMA LIMPIADORA INTRA PREMIO 500 ML','category_id'=>'5','unit_id'=>'1']);
        Product::create(['code'=>'CRE00031','name'=>'CREMA LIMPIADORA INTRA PREMIO SPARY 360 ML','category_id'=>'5','unit_id'=>'1']);
        Product::create(['code'=>'DES00032','name'=>'DESATORADOR LIQUIDO SAPOLIO BAÑO X 980 ML','category_id'=>'6','unit_id'=>'1']);
        Product::create(['code'=>'DES00033','name'=>'DESATORADOR TIRABUZON MANGO MADERA C/JEBE NEGRO','category_id'=>'6','unit_id'=>'1']);
        Product::create(['code'=>'DET00034','name'=>'DETERGENTE ARIEL X 2.8 KG','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DET00035','name'=>'DETERGENTE SAPOLIO X 13.50 KG','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DET00036','name'=>'DETERGENTE SAPOLIO X 2 KG','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DET00037','name'=>'DETERGENTE SAPOLIO X 4 KG','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DET00038','name'=>'DETERGENTE SAPOLIO X 14 KG','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DIS00039','name'=>'DISPENSADOR HIGIENICO JUMBO EBRIEL BLANCO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'DIS00040','name'=>'DISPENSADOR HIGIENICO JUMBO EBRIEL HUMO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'DIS00041','name'=>'DISPENSADOR HIGIENICO JUMBO EBRIEL NEGRO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'DIS00042','name'=>'DISPENSADOR HIGIENICO JUMBO MASTER CLEAN BLANCO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'DIS00043','name'=>'DISPENSADOR JABON LIQUIDO EBRIEL ACERO','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DIS00044','name'=>'DISPENSADOR JABON LIQUIDO EBRIEL DOBLE SISTEMA','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DIS00045','name'=>'DISPENSADOR JABON LIQUIDO MASTER CARS DOBLE SISTEMA','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'DIS00046','name'=>'DISPENSADOR TOALLA AUTOCORTE EBRIEL BLANCO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'DIS00047','name'=>'DISPENSADOR TOALLA PALANCA EBRIEL BLANCO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'ESC00048','name'=>'ESCOBON HUDE','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'ESP00049','name'=>'ESPONJA VERDE SCOTT BRITE DOBLE  X 7 UND','category_id'=>'22','unit_id'=>'1']);
        Product::create(['code'=>'ESP00050','name'=>'ESPONJA VERDE SCOTT BRITE CAJ X 15 UND','category_id'=>'22','unit_id'=>'1']);
        Product::create(['code'=>'ESP00051','name'=>'ESPONJA VERDE SCOTT BRITE X UND','category_id'=>'22','unit_id'=>'1']);
        Product::create(['code'=>'FRA00052','name'=>'FRANELA AMARILLA X MT','category_id'=>'14','unit_id'=>'1']);
        Product::create(['code'=>'GUA00053','name'=>'GUANTES ETERNA CALIBRE 25 T/8 NEGRO','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00054','name'=>'GUANTES PROTEX CALIBRE 25 NEGRO T/8','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00055','name'=>'GUANTES PROTEX CALIBRE 35 NEGRO T/8','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00056','name'=>'GUANTES QUIRURGICO CAJ T/M','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00057','name'=>'GUANTES QUIRURGICO FAMILY DOCTOR  CAJ T/L','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00058','name'=>'GUANTES VIRUTEX CONVENIENTE AMARILLO T/S 7','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00059','name'=>'GUANTES VIRUTEX CONVENIENTE AMARILLO T/M 8','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'GUA00060','name'=>'GUANTES VIRUTEX CONVENIENTE AMARILLO T/L 9','category_id'=>'10','unit_id'=>'1']);
        Product::create(['code'=>'HAR00061','name'=>'HARPIC LIQUIDO NEGRO 760 ML','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'HIG00062','name'=>'HIGIENICO ELITE X 500 MT X 4 ROLLOS','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'HIG00063','name'=>'HIGIENICO ELITE DOBLE HOJA 250 MT  PAQ X 06 ROLLOS','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'HIG00064','name'=>'HIGIENICO SUAVE PAQ X 40 UND','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'HON00065','name'=>'HONGUITO','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'JAB00066','name'=>'JABON DE TOCADOR NEKO X 125 GR','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'JAB00067','name'=>'JABON DE TOCADOR PROTEX X 125 GR','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'JAB00068','name'=>'JABON ESPUMA EBRIEL SACHET X 800 ML','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'JAB00069','name'=>'JABON LIQUIDO EBRIEL ANTIBACTERIAL SACHET X 800 ML','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'JAB00070','name'=>'JABON LIQUIDO EBRIEL SACHET X 800 ML','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'JAB00071','name'=>'JABON LIQUIDO KAZVEL LAVANDA X GALON','category_id'=>'2','unit_id'=>'1']);
        Product::create(['code'=>'LAV00072','name'=>'LAVAVAJILLA AYUDIN LIQUIDO LIMON 900 ML','category_id'=>'19','unit_id'=>'1']);
        Product::create(['code'=>'LAV00073','name'=>'LAVAVAJILLA AYUDIN PASTA 750 GM','category_id'=>'19','unit_id'=>'1']);
        Product::create(['code'=>'LAV00074','name'=>'LAVAVAJILLA AYUDIN PASTA 950 GM','category_id'=>'19','unit_id'=>'1']);
        Product::create(['code'=>'LAV00075','name'=>'LAVAVAJILLA LIQUIDA KAZVEL','category_id'=>'19','unit_id'=>'1']);
        Product::create(['code'=>'LAV00076','name'=>'LAVAVAJILLA SAPOLIO LIQUIDO GALON X 5 LT','category_id'=>'19','unit_id'=>'1']);
        Product::create(['code'=>'LEJ00077','name'=>'LEJIA CLOROX X GALON','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'LEJ00078','name'=>'LEJIA GALÓN 5%','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'LIM00079','name'=>'LIMPIATODO KAZVEL X GALÓN','category_id'=>'5','unit_id'=>'1']);
        Product::create(['code'=>'LUS00080','name'=>'LUSTRA MUEBLE PREMIO DE MADERA 5 EN 1 SPRAY','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'MAS00081','name'=>'MASCARILLA KN-95 BLANCA MAYFIELD CAJ X 10','category_id'=>'11','unit_id'=>'1']);
        Product::create(['code'=>'MAT00082','name'=>'MATA MOSCAS Y ZANCUDOS SAPOLIO SPRAY X 360 ML','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'PAÑ00083','name'=>'PAÑO MICROFIBRA CHICO','category_id'=>'14','unit_id'=>'1']);
        Product::create(['code'=>'PAÑ00084','name'=>'PAÑO MICROFIBRA GRANDE','category_id'=>'14','unit_id'=>'1']);
        Product::create(['code'=>'PAÑ00085','name'=>'PAÑO VIRUTEX ABSORBENTE AMARILLO PAQ X 20','category_id'=>'14','unit_id'=>'1']);
        Product::create(['code'=>'PAP00086','name'=>'PAPEL HIGIENICO JUMBO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'PAP00087','name'=>'PAPEL HIGIENICO JUMBO 24 GR 9 ANCHO X 24 DIAMETRO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'PAP00088','name'=>'PAPEL SABANILLA ELITE PAQ X 02 X 100 M','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'PAP00089','name'=>'PAPEL TOALLA JUMBO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'PAP00090','name'=>'PAPEL TOALLA ROLLO','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'PAS00091','name'=>'PASTILLA BAÑO MR JOSSY FRESA','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'PAS00092','name'=>'PASTILLA BAÑO SAPOLIO AZUL WC X UND','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'PAS00093','name'=>'PASTILLA BAÑO SAPOLIO AZUL WC X 2 UND','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'PIN00094','name'=>'PINO NATURAL KAZVEL X GALON','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'PLU00095','name'=>'PLUMERO DE TELA','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'QUI00096','name'=>'QUITA GRASA KAZVEL X GALON','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'QUI00097','name'=>'QUITASARRO KAZVEL WC X GALON','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'SAC00098','name'=>'SACAGRASA SAPOLIO GALON X 5 LT','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'SEC00099','name'=>'SECADOR DE MANO WORK DRYER AUTOMATICO','category_id'=>'23','unit_id'=>'1']);
        Product::create(['code'=>'SIL00100','name'=>'SILICONA KANAO','category_id'=>'20','unit_id'=>'1']);
        Product::create(['code'=>'SIL00101','name'=>'SILICONA SAPOLIO SPRAY CHERRY 360 ML','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'SIL00102','name'=>'SILICONA SAPOLIO SPRAY','category_id'=>'3','unit_id'=>'1']);
        Product::create(['code'=>'SIL00103','name'=>'SILLITA NIÑO','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'SUA00104','name'=>'SUAVISANTE AMOR 5 LT','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'TAC00105','name'=>'TACHO PAPELERA AUTOMATICA DANUBIO # 25 REY AMARILLO','category_id'=>'17','unit_id'=>'1']);
        Product::create(['code'=>'TAC00106','name'=>'TACHO PAPELERA AUTOMATICA DANUBIO # 25 REY NEGRO','category_id'=>'17','unit_id'=>'1']);
        Product::create(['code'=>'TAC00107','name'=>'TACHO PAPELERA AUTOMATICA DANUBIO # 25 REY ROJO','category_id'=>'17','unit_id'=>'1']);
        Product::create(['code'=>'TAC00108','name'=>'TACHO PAPELERA BODEGUITA VAIVEN 75 LT ECOBASA','category_id'=>'17','unit_id'=>'1']);
        Product::create(['code'=>'TAP00109','name'=>'TAPA DE INODORO ELONGADO FIORI 46.5','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'TAP00110','name'=>'TAPA DE INODORO REDONDO TREBOL  42','category_id'=>'24','unit_id'=>'1']);
        Product::create(['code'=>'TOA00111','name'=>'TOALLA NOVA NARANJA PAQ X 12 ROLLOS','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'TOA00112','name'=>'TOALLA INTERFOLIADO SUMAC CAJ X 20 X 175 HOJAS','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'PAP00113','name'=>'PAPEL TOLLA INTERFOLIADO ELITE DOBLE HOJA XL','category_id'=>'8','unit_id'=>'1']);
        Product::create(['code'=>'TRA00114','name'=>'TRAPEADOR MICROFIBRA CON OJAL','category_id'=>'13','unit_id'=>'1']);
        Product::create(['code'=>'TRA00115','name'=>'TRAPO INDUSTRIAL BLANCOX KG','category_id'=>'14','unit_id'=>'1']);

    }
}
